---
- name: install pyenv for managing python versions
  homebrew:
    name: pyenv
    state: present

- name: install pyenv-virtualenv for managing virtualenvs with pyenv
  homebrew:
    name: pyenv-virtualenv
    state: latest

- name: Activate pyenv and pyenv-virtualenv plugin in bash script
  blockinfile:
    path: "{{ local_home }}/.bash_profile"
    create: yes
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PYENV_VERSION=3.7.0
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)"
  when: ansible_env.SHELL == '/bin/bash'


- name: install docker
  homebrew_cask:
    name: docker
    state: present

- name: register the path of the python version for pyenv
  stat:
    path: "{{ ae_pyenv_versions_path }}/{{ ae_python_version }}"
  register: pyenv_python

- name: "install pyenv managed Python version {{ ae_python_version }}"
  shell: "pyenv install {{ ae_python_version }}"
  when: not pyenv_python.stat.exists

- name: Create Projects directory in user's documents directory
  file:
    path: "{{ ae_projects_home }}"
    state: directory

- name: clone down the automation engineer project repos from GitHub
  git:
    repo: "{{ item }}"
    dest: "{{ ae_projects_home}}/{{ item.split('/')[-1] }}"
  with_items: "{{ ae_project_repos }}"
