---
- name: install pyenv for managing python versions
  homebrew:
    name: pyenv
    state: present

- name: install pyenv-virtualenv for managing virtualenvs with pyenv
  homebrew:
    name: pyenv-virtualenv
    state: latest

- name: Activate pyenv and pyenv-virtualenv plugin in bash script
  blockinfile:
    path: /etc/network/interfaces
    block: |
      iface eth0 inet static
          address 192.0.2.23
          netmask 255.255.255.0

- name: install docker
  homebrew_cask:
    name: docker
    state: present

- name: register the path of the python version for pyenv
  stat:
    path: "{{ ae_pyenv_versions_path }}/{{ ae_python_version }}"
  register: pyenv_python

- name: "install pyenv managed Python version {{ ae_python_version }}"
  shell: "pyenv install {{ ae_python_version }}"
  when: not pyenv_python.stat.exists

- name: Create Projects directory in user's documents directory
  file:
    path: "{{ ae_projects_home }}"
    state: directory

- name: clone down the automation engineer project repos from GitHub
  git:
    repo: "{{ item }}"
    dest: "{{ ae_projects_home}}"
  with_items: "{{ ae_project_repos }}"
