---
- name: install java via brew
  homebrew_cask:
    name: java
    state: present

- name: install libmagic
  homebrew:
    name: libmagic
    state: present

- name: install nebuchadnezzar
  pip:
    name: nebuchadnezzar
    state: latest
