---
- name: check if the neb home directory exists
  stat:
    path: "{{ neb_home }}"
  register: neb_home

- name: create neb home directory
  file:
    state: directory
    path: "{{ neb_home }}"
    mode: 0750
  when: not neb_home.stat.exists

- name: install java via brew
  homebrew_cask:
    name: java
    state: present

- name: install nebuchadnezzar via pip
  pip:
    name: nebuchadnezzar
    state: present

- name: install atom editor via brew
  homebrew_cask:
    name: atom
    state: present
    install_options: 'appdir=/Applications'

- name: Fetch the cnx RNG Schema files
  get_url:
    dest: "{{ cnxml_rng_download_path }}/{{ cnxml_rng_pkg_name }}" 
    url: "{{ cnxml_rng_download_url }}"
    mode: 0755

- name: untar the cnxml archive
  unarchive:
    src: "{{ cnxml_rng_download_path }}/{{ cnxml_rng_pkg_name }}"
    dest: "{{ neb_home }}"

- name: install atom packages via shell command
  shell: >
    apm list --bare | grep -E '{{ item }}@' && echo 'Already installed.'
    || apm install '{{ item }}'
  register: apm_result
  with_items: "{{ atom_packages }}"
  changed_when: "'Already installed.' not in apm_result.stdout"

- name: copy over the atom config
  template: 
    remote_src: yes
    src: config.cson.j2
    dest: '~/.atom/config.cson'
    mode: u=rw,go=