---
- name: bootstrapping your machine to OpenStax standards
  hosts: localhost
  vars:
    local_home: "{{ lookup('env','HOME') }}"
  tasks:
    - import_role:
        name: osx-common
      when: ansible_os_family == 'Darwin'
    - import_role:
        name: content-manager
      when: openstax_role == 'content_manager'

